Pull request de prueba
foliolo/GitTest pull request #12
Opened 2022-09-19 23:29 UTC by Isabel9422

I have fixed files which are on master branch

2022-09-19 23:30 UTC, foliolo requested changes
Revisa estos cambios

2022-09-19 23:30 UTC, foliolo commented on myfile.txt
> +MY FILE
Esto deberia ir al final del fichero

2022-09-20 00:00 UTC, Isabel9422 commented on myfile.txt
> +MY FILE
Done

2022-09-20 00:01 UTC, foliolo commented on myfile.txt
> +MY FILE
Perfecto! Gracias 👍

2022-09-20 00:02 UTC, foliolo commented
@Isabel9422 Revisa que tienes conflictos!! Esto aun no se puede mergear!
La proxima vez sube los cambios asegurándote que la rama está actualizada!!!! 😉

2022-09-20 01:15 UTC, Isabel9422 commented
Trabajo realizado !

2022-09-20 01:17 UTC, foliolo approved these changes
Perfecto, ahora si! 🚀

2022-09-20 01:18 UTC, merged